project:
  type: website

website:
  title: "Izzul Fattah Aji Pratama - Communicating With Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/apra0095
      - text: "About"
        href: about.qmd
format:
  html:
    theme: cosmo
    css: styles.css



