project:
  type: website
  output-dir: docs

website:
  title: "Izzul Fattah Aji Pratama - Communicating With Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/apra0095
format:
  html:
    theme: cosmo
    css: styles.css



