project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - "posts/*/index.qmd"

website:
  title: "Izzul Fattah Aji Pratama - Communicating With Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/apra0095

format:
  html:
    theme: cosmo
    css: styles.css




