project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - "posts/*/index.qmd"

website:
  title: "Aji Pratama's Academic Blogpost"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/apra0095

  page-footer:
    background: dark
    left: |
      **Izzul Fattah Aji Pratama**<br>
      Master of Business Analytics (Monash University)<br>
      Communicating With Data<br>
      © 2025 Izzul Fattah Aji Pratama
    right:
      - icon: github
        href: https://github.com/apra0095
      - icon: envelope
        href: mailto:apra0095@student.monash.edu
      - icon: linkedin
        href: https://www.linkedin.com/in/aji-pratama-0b8508180/
      - text: "Melbourne, VIC, Australia"

format:
  html:
    theme: cosmo
    css: styles.css



